version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Abhishek
      MYSQL_DATABASE: carrental
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAbhishek"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./carrental-backend-main
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carrental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abhishek
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8081"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./carrental-frontend-main
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data:
